name: demandium_provider
description: A new Flutter project.


publish_to: 'none' #

version: 1.0.0+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  get: ^4.7.2
  intl: ^0.20.2
  path: ^1.9.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  country_code_picker: 3.1.0
  pin_code_fields: ^8.0.1
  flutter_widget_from_html_core: ^0.16.0
  flutter_typeahead: ^5.2.0
  shimmer_animation: ^2.2.2
  fl_chart: ^0.70.2
  dotted_border: ^2.1.0
  flutter_local_notifications: ^18.0.1
  file_picker: ^9.0.2
  pdf: ^3.11.1
  open_file: ^3.5.10
  flutter_downloader: ^1.12.0
  permission_handler: ^11.4.0
  printing: ^5.14.2
  expandable_bottom_sheet: ^1.1.1+1
  shimmer: ^3.0.0
  currency_text_input_formatter: ^2.2.8
  graphic: ^2.5.1
  syncfusion_flutter_charts: ^28.2.9
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  flutter_slidable: ^4.0.0
  flutter_switch: ^0.3.2
  just_the_tooltip: ^0.0.12
  flutter_inappwebview: ^6.1.5
  universal_html: ^2.2.4
  scroll_to_index: ^3.0.1
  photo_view: ^0.15.0
  phone_numbers_parser: ^9.0.3
  path_provider: ^2.1.5
  video_player: ^2.9.3
  chewie: ^1.10.0
  firebase_auth: ^6.0.1
  readmore: ^3.0.0
  showcaseview: ^4.0.1
  skeletonizer: ^2.1.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/language/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/font/Roboto-Light.ttf
          weight: 300
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
